fillers = [
  "а",
  "аа",
  "ааа",
  "э",
  "ээ",
  "э-э",
  "м",
  "эм",
  "мм",
  "ну",
  "вот",
  "это",
  "как бы",
  "типа",
  "короче",
  "значит",
  "так сказать",
  "в общем",
  "слушай",
  "смотри",
  "да",
  "ладно",
  "ну вот",
]
