import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const MAX_BUILD = 99;

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const mode = process.argv[2];

if (mode !== "dev" && mode !== "prod") {
  console.error("usage: node scripts/bump-version.mjs <dev|prod>");
  process.exit(1);
}

function bumpVersion(version) {
  version.build += 1;
  if (version.build > MAX_BUILD) {
    version.minor += 1;
    version.build = 0;
  }
  return version;
}

const versionPath = path.join(root, "version.json");
const version = bumpVersion(JSON.parse(readFileSync(versionPath, "utf8")));

const semver = `${version.major}.${version.minor}.${version.build}`;
const display = semver;

writeFileSync(versionPath, `${JSON.stringify(version, null, 2)}\n`, "utf8");

const packageJsonPath = path.join(root, "package.json");
const packageJson = JSON.parse(readFileSync(packageJsonPath, "utf8"));
packageJson.version = semver;
writeFileSync(packageJsonPath, `${JSON.stringify(packageJson, null, 2)}\n`, "utf8");

const cargoTomlPath = path.join(root, "src-tauri", "Cargo.toml");
let cargoToml = readFileSync(cargoTomlPath, "utf8");
cargoToml = cargoToml.replace(
  /^version = "[^"]+"$/m,
  `version = "${semver}"`,
);
writeFileSync(cargoTomlPath, cargoToml, "utf8");

const tauriConfPath = path.join(root, "src-tauri", "tauri.conf.json");
const tauriConf = JSON.parse(readFileSync(tauriConfPath, "utf8"));
tauriConf.version = semver;
writeFileSync(tauriConfPath, `${JSON.stringify(tauriConf, null, 2)}\n`, "utf8");

const generatedDir = path.join(root, "src", "generated");
mkdirSync(generatedDir, { recursive: true });
const versionTs = `// Generated by scripts/bump-version.mjs — do not edit manually.
export const APP_VERSION_DISPLAY = ${JSON.stringify(display)};
export const APP_VERSION_SEMVER = ${JSON.stringify(semver)};
export const APP_VERSION_MAJOR = ${version.major};
export const APP_VERSION_MINOR = ${version.minor};
export const APP_VERSION_BUILD = ${version.build};
`;
writeFileSync(path.join(generatedDir, "version.ts"), versionTs, "utf8");

console.log(`Version bumped (${mode}): ${display}`);
