import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const version = JSON.parse(readFileSync(path.join(root, "version.json"), "utf8"));
const semver = `${version.major}.${version.minor}.${version.build}`;

const packageJsonPath = path.join(root, "package.json");
const packageJson = JSON.parse(readFileSync(packageJsonPath, "utf8"));
packageJson.version = semver;
writeFileSync(packageJsonPath, `${JSON.stringify(packageJson, null, 2)}\n`, "utf8");

let cargoToml = readFileSync(path.join(root, "src-tauri", "Cargo.toml"), "utf8");
cargoToml = cargoToml.replace(/^version = "[^"]+"$/m, `version = "${semver}"`);
writeFileSync(path.join(root, "src-tauri", "Cargo.toml"), cargoToml, "utf8");

const tauriConfPath = path.join(root, "src-tauri", "tauri.conf.json");
const tauriConf = JSON.parse(readFileSync(tauriConfPath, "utf8"));
tauriConf.version = semver;
writeFileSync(tauriConfPath, `${JSON.stringify(tauriConf, null, 2)}\n`, "utf8");

const generatedDir = path.join(root, "src", "generated");
mkdirSync(generatedDir, { recursive: true });
writeFileSync(
  path.join(generatedDir, "version.ts"),
  `// Generated by scripts/bump-version.mjs — do not edit manually.
export const APP_VERSION_DISPLAY = ${JSON.stringify(semver)};
export const APP_VERSION_SEMVER = ${JSON.stringify(semver)};
export const APP_VERSION_MAJOR = ${version.major};
export const APP_VERSION_MINOR = ${version.minor};
export const APP_VERSION_BUILD = ${version.build};
`,
  "utf8",
);

console.log(`Synced version: ${semver}`);
