#!/usr/bin/env python3
"""Expand ru_lexicon_forms.txt using pymorphy3 (optional dev/CI step).

Usage:
  pip install pymorphy3 pymorphy3-dicts-ru
  python tools/speech_analysis/expand_ru_lexicon.py --seeds tools/speech_analysis/lexicon_seeds_ru.txt

Writes: src-tauri/resources/speech_analysis/ru_lexicon_forms.txt
"""

from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "src-tauri/resources/speech_analysis/ru_lexicon_forms.txt"
DEFAULT_SEEDS = Path(__file__).with_name("lexicon_seeds_ru.txt")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--seeds", type=Path, default=DEFAULT_SEEDS)
    args = parser.parse_args()
    try:
        import pymorphy3
    except ImportError as exc:
        raise SystemExit(
            "pymorphy3 not installed; pip install pymorphy3 pymorphy3-dicts-ru"
        ) from exc

    morph = pymorphy3.MorphAnalyzer()
    seeds = [
        line.strip()
        for line in args.seeds.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.startswith("#")
    ]
    forms: set[str] = set()
    for seed in seeds:
        parsed = morph.parse(seed)
        if not parsed:
            continue
        lex = parsed[0].lexeme
        for item in lex:
            w = item.word.lower()
            if len(w) >= 2:
                forms.add(w)

    header = "# Generated by expand_ru_lexicon.py — do not hand-edit unless re-run.\n"
    body = "\n".join(sorted(forms))
    OUT.write_text(header + body + "\n", encoding="utf-8")
    print(f"Wrote {len(forms)} forms to {OUT}")


if __name__ == "__main__":
    main()
